"""
Django settings for genius_harmony project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-bso!4pb3np1x$*^xp8wbfk766d)(&)6k=u@f@zj1e@kkxxnmfo')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'corsheaders',
    # Celery & Redis
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'genius_harmony.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'genius_harmony.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuration pour PostgreSQL en production, SQLite en développement
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration du stockage des fichiers media avec Render Disk
# Render Disk est monté à /opt/render/project/src/media pour persistance
import os

# Détecter si on est sur Render avec un disk monté
RENDER_DISK_PATH = '/opt/render/project/src/media'
if os.path.exists(RENDER_DISK_PATH):
    MEDIA_ROOT = RENDER_DISK_PATH
    print(f"✅ [INFO] Using Render Disk for persistent media storage: {MEDIA_ROOT}")
else:
    # Développement local
    MEDIA_ROOT = BASE_DIR / 'media'
    print(f"[INFO] Using local media storage: {MEDIA_ROOT}")

MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv()
)

# Allow credentials for JWT authentication
CORS_ALLOW_CREDENTIALS = True

# ========================================
# ODOO INTEGRATION CONFIGURATION
# ========================================
ODOO_ENABLED = config('ODOO_ENABLED', default=False, cast=bool)
ODOO_HOST = config('ODOO_HOST', default='')
ODOO_PORT = config('ODOO_PORT', default=443, cast=int)
ODOO_PROTOCOL = config('ODOO_PROTOCOL', default='jsonrpc+ssl')
ODOO_DB = config('ODOO_DB', default='')
ODOO_USERNAME = config('ODOO_USERNAME', default='')
ODOO_PASSWORD = config('ODOO_PASSWORD', default='')

# Token secret pour sécuriser les webhooks Odoo → Django
# Générer avec: python -c "import secrets; print(secrets.token_urlsafe(32))"
ODOO_WEBHOOK_SECRET = config('ODOO_WEBHOOK_SECRET', default='')

# ========================================
# REDIS CONFIGURATION (Cache + Celery Broker)
# ========================================
REDIS_URL = config('REDIS_URL', default='')

# Cache configuration with fallback
# Use Redis if configured, otherwise fall back to local memory cache
if REDIS_URL and (REDIS_URL.startswith('redis://') or REDIS_URL.startswith('rediss://')):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'genius_harmony',
            'TIMEOUT': 300,  # 5 minutes par défaut
        }
    }
    print("✅ [INFO] Using Redis cache")
else:
    # Fallback to local memory cache if Redis is not configured
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'genius-harmony-cache',
            'TIMEOUT': 300,
        }
    }
    print("⚠️ [WARNING] Redis not configured, using local memory cache (not suitable for production)")

# ========================================
# CELERY CONFIGURATION (Async Tasks)
# ========================================
# Only configure Celery if Redis URL is valid
if REDIS_URL and (REDIS_URL.startswith('redis://') or REDIS_URL.startswith('rediss://')):
    CELERY_BROKER_URL = REDIS_URL
    print("✅ [INFO] Celery broker configured with Redis")
else:
    CELERY_BROKER_URL = None
    print("⚠️ [WARNING] Celery broker not configured - async tasks will be disabled")

CELERY_RESULT_BACKEND = 'django-db'  # Stocke les résultats dans PostgreSQL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max par task

# Celery Beat (scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ========================================
# LOGGING CONFIGURATION
# ========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
