# Generated by Django 5.2.9 on 2025-12-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pole",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("film", "Film"),
                            ("court_metrage", "Court métrage"),
                            ("web_serie", "Web série"),
                            ("event", "Event"),
                            ("atelier_animation", "Atelier/Animation"),
                            ("musique", "Musique"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("en_revision", "En révision"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("odoo_project_id", models.IntegerField(blank=True, null=True)),
                ("odoo_invoice_id", models.IntegerField(blank=True, null=True)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin_prevue", models.DateField(blank=True, null=True)),
                ("date_fin_reelle", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chef_projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets_geres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projets_membre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets",
                        to="core.pole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("fichier", models.FileField(upload_to="documents/%Y/%m/%d/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("scenario", "Scénario"),
                            ("contrat", "Contrat"),
                            ("brief", "Brief"),
                            ("moodboard", "Moodboard"),
                            ("rush", "Rush / Footage"),
                            ("montage", "Montage"),
                            ("export_final", "Export final"),
                            ("presskit", "Presskit"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploade_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                        ],
                        default="a_faire",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigne_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taches_assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches",
                        to="core.projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
                "ordering": ["deadline", "-priorite"],
            },
        ),
    ]
