# Generated by Django 5.2.9 on 2025-12-09 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_pole_id_alter_profile_id_projet_document_tache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pole",
            name="chef",
            field=models.ForeignKey(
                blank=True,
                help_text="Chef de pôle désigné",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pole_dirige",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pole",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("chef_pole", "Chef de pôle"),
                    ("membre", "Membre"),
                    ("stagiaire", "Stagiaire"),
                    ("technicien", "Technicien"),
                    ("artiste", "Artiste"),
                    ("client", "Client"),
                    ("partenaire", "Partenaire"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tache",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
