# Generated by Django 5.2.9 on 2025-12-18 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pole_chef_alter_document_id_alter_pole_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur qui a créé le projet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projets_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
