# Generated by Django 5.2.9 on 2025-12-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_projet_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
