# Generated by Django 5.2.9 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("chef_pole", "Chef de pôle"),
                    ("membre", "Membre"),
                    ("stagiaire", "Stagiaire"),
                    ("artiste", "Artiste"),
                    ("client", "Client"),
                    ("partenaire", "Partenaire"),
                ],
                max_length=20,
            ),
        ),
    ]
