# Generated by Django 5.2.9 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_technicien_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="chef_projet_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "En attente"),
                    ("accepted", "Accepté"),
                    ("declined", "Refusé"),
                ],
                help_text="Statut d'acceptation du chef de projet",
                max_length=20,
                null=True,
            ),
        ),
    ]
