# Generated by Django 5.2.9 on 2025-12-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_profile_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("scenario", "Scénario"),
                    ("contrat", "Contrat"),
                    ("budget", "Budget"),
                    ("planning", "Planning"),
                    ("brief", "Brief"),
                    ("moodboard", "Moodboard"),
                    ("rush", "Rush / Footage"),
                    ("montage", "Montage"),
                    ("export_final", "Export final"),
                    ("media", "Media"),
                    ("presskit", "Presskit"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=30,
            ),
        ),
    ]
