# Generated by Django 6.0 on 2025-01-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_add_document_types"),
    ]

    operations = [
        # Add odoo_task_id field to Tache model
        migrations.AddField(
            model_name="tache",
            name="odoo_task_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="ID de la tâche dans Odoo"
            ),
        ),
        # Create Notification model
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deadline_3days", "📅 Deadline dans 3 jours"),
                            ("deadline_1day", "⚠️ Deadline demain"),
                            ("deadline_today", "🔴 Deadline aujourd'hui"),
                            ("deadline_overdue", "❌ Tâche en retard"),
                            ("project_assigned", "🎯 Nouveau projet assigné"),
                            ("task_assigned", "📋 Nouvelle tâche assignée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.projet",
                    ),
                ),
                (
                    "tache",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tache",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        # Add indexes for performance
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"],
                name="core_notifi_user_id_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"],
                name="core_notifi_user_id_is_read_idx",
            ),
        ),
    ]
